apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane
automountServiceAccountToken: true
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: control-plane
  namespace: default
subjects:
  - kind: ServiceAccount
    name: control-plane
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-pv
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - persistentvolumes
      - namespaces
    verbs: ["*"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-pv
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-pv
subjects:
  - kind: ServiceAccount
    name: control-plane
    namespace: default
