apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: manifest-config
  namespace: default
  envs:
    - deployment.properties
resources:
    - account.yaml
    - deployment.yaml
    - service.yaml
