apiVersion: v1
kind: Service
metadata:
  name: manifest
  labels:
    app: manifest-deployment
    service: manifest
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: manifest
  type: LoadBalancer
